### ISSUE TITLE
Where to put code for new feature?

### ISSUE THREAD

**Issue by pfitz** [odarriba/elixir_jobs#11]
Hi !
I'd like to make  a pr which adds the current ```place_type``` to the twitter message. 
In theorie I could write the hole code in the ```Twitter``` module. But it would duplicate the code for humanizing the ```place_type``` enum which is already in the ```OfferView``` module. 
The function in question is ```human_get_place/2```.

Now my question is where I could move the code out of the ```OfferView```? Inside a new module called ```HumanizeHelper``` ? Where should I put this file?

Background: I am on the search for a remote elixir job and would really like to see if a job offer is open for remote work.

**Comment by odarriba** [comment]
Hey! Thanks for reaching out!

Well, there are different possibilities:

1. Just call view function or import it.
2. As you say, move it to a helper.

I really like the idea of creating a module for this, and changing the references to these functions in order to point to the new helper.

And i wish you luck finding the right job (and I hope ElixirJobs can help you!)
